#!/bin/sh

one=`uptime | awk '{print $8}' | cut -c -4`
five=`uptime | awk '{print $9}' | cut -c -4`
fifteen=`uptime | awk '{print $10}' | cut -c -4`

echo "$(printf '{"1min": %s, "5min": %s, "15min": %s}' $one $five $fifteen)"
