#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw/$Bin/;
use lib "$Bin/lib";
use JSON::Tiny qw/to_json/;

my %stats;
if (
    -e "/proc/sys/net/netfilter"
    && -e "/proc/sys/net/netfilter/nf_conntrack_count"
    && -e "/proc/sys/net/netfilter/nf_conntrack_max"
) {
    open my $active_fh, "<", "/proc/sys/net/netfilter/nf_conntrack_count";
    open my $max_fh, "<", "/proc/sys/net/netfilter/nf_conntrack_max";
    my $active = <$active_fh>;
    my $max = <$max_fh>;

    chomp $active;
    chomp $max;

    $stats{nf_conntrack} = {
        active  => $active +0,
        max     => $max +0,
    };
}

print to_json( \%stats ), "\n";
