#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw/$Bin/;
use lib "$Bin/lib";
use JSON::Tiny qw/to_json/;

my $interfaces = {};
my $basename_reg = qr|.*/(.+)|;

for my $interface_dir ( </sys/class/net/*> ) {
    my ( $interface ) = ( $interface_dir =~ m/$basename_reg/ );

    $interfaces->{ $interface } = {};

    for my $stat_file ( <$interface_dir/statistics/*> ) {
        open my $fh, '<', $stat_file;
        my $stat_value = <$fh>;
        chomp $stat_value;

        my ( $stat ) = ( $stat_file =~ m/$basename_reg/ );

        $interfaces->{ $interface }->{ $stat } = $stat_value;
    }
}

print to_json( $interfaces ), "\n";
