#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw/$Bin/;
use lib "$Bin/lib";
use JSON::Tiny;

my %state_counts;
my @ss = `ss`;
shift @ss; #this one is column names

foreach my $row ( @ss ) {
    my $state = [split /\s+/, $row]->[1];
    $state_counts{ $state }++;
}
print JSON::Tiny::to_json( \%state_counts );
