#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw/$Bin/;
use lib "$Bin/lib";
use JSON::Tiny qw/to_json/;

my %processes;
my @ps = `ps aux`;
shift @ps; #this one is column names

foreach my $row ( @ps ) {
    my @split_row = split /\s+/, $row;

    my $user = $split_row[0];
    my $pid = $split_row[1];
    my $cpu = $split_row[2];
    my $mem = $split_row[3];
    my $process_name = join ' ', @split_row[10 .. $#split_row ];

    #skip kernel processes
    next if $process_name =~ /^\[.*\]$/;

    $processes{pids}{ $pid } = {
        user            => $user,
        process_name    => $process_name,
        'cpu%'          => $cpu +0,
        'mem%'          => $mem +0,
    };
}

$processes{count} = scalar keys %{$processes{pids}};

print to_json( \%processes );
